// export const senior_secondary_questions = [
//   {
//     title: "Question 1",
//     prompt: "Which stream and subjects did you choose after 10th class?",
//     name: "stream_chosen",
//     options: ["🔬 Science Stream", "🧠 Arts Stream", "💼 Commerce Stream"],
//   },
//   {
//     title: "Question 2",
//     prompt: "What was the main reason you chose these subjects?",
//     name: "reason_for_subject_choice",
//     options: [
//       "❤️ Genuine Interest",
//       "📊 Good marks in 10th in related subjects",
//       "👨‍👩‍👧 Parental/Societal Expectations",
//       "🧑‍🤝‍🧑 Inspired by friends/peer pressure",
//       "🛡️ Seemed like a 'safe' choice",
//       "😕 Did not have much clarity, chose randomly",
//       "✍️ Other (please specify)",
//     ],
//   },
//   {
//     title: "Question 3",
//     prompt: "Are you confident about the subjects you chose?",
//     name: "subject_confidence_level",
//     options: [
//       "✅ Very confident",
//       "⚖️ Somewhat confident",
//       "❌ Not confident at all",
//     ],
//   },
//   {
//     title: "Question 4",
//     prompt:
//       "If you were given a totally free hand, which subjects would you have loved to study?",
//     name: "dream_subjects",
//     options: [
//       "🔬 Physics or Chemistry",
//       "🧬 Biology",
//       "➗ Mathematics",
//       "📘 Business Studies",
//       "📒 Accountancy",
//       "📉 Economics",
//       "🏛️ History, Political Science, Sociology, Current Affairs",
//       "🧠 Psychology",
//       "🌍 Geography",
//       "✍️ Other (please specify)",
//     ],
//   },
//   {
//     title: "Question 5",
//     prompt: "Which subjects do you truly enjoy studying?",
//     name: "enjoyed_subjects_multiple",
//     options: [
//       "🔬 Physics",
//       "⚗️ Chemistry",
//       "🧬 Biology",
//       "➗ Mathematics",
//       "📘 Business Studies",
//       "📒 Accountancy",
//       "📉 Economics",
//       "🏛️ History",
//       "🗳️ Political Science",
//       "🧑‍🤝‍🧑 Sociology",
//       "🧠 Psychology",
//       "🌍 Geography",
//       "🎨 Fine Arts",
//       "✍️ Other (please specify)",
//     ],
//   },
//   {
//     title: "Question 6",
//     prompt: "Which activities do you naturally enjoy the most?",
//     name: "naturally_enjoyed_activities_multiple",
//     options: [
//       "🗣️ Debating, public speaking",
//       "🧩 Solving puzzles, logical problems",
//       "✍️ Designing, drawing, creativity",
//       "👩‍💼 Managing teams, leading projects",
//       "📊 Analyzing numbers/data",
//       "📝 Writing stories, articles, content",
//       "🤝 Helping people, counseling",
//       "🔬 Experimenting, doing science projects",
//       "💻 Coding, building apps/websites",
//       "📢 Business/marketing related activities",
//       "✍️ Other (please specify)",
//     ],
//   },
//   {
//     title: "Question 7",
//     prompt:
//       "If you imagine yourself 5–10 years from now, which profession excites you the most?",
//     name: "most_exciting_profession",
//     options: [
//       "🩺 Doctor/Medical Professional",
//       "🛠️ Engineer (Software, Mechanical, Civil, etc.)",
//       "⚖️ Lawyer/Legal Expert",
//       "👗 Fashion Designer",
//       "🧑‍💼 Entrepreneur/Business Owner / 🏛️ Architect",
//       "👩‍🏫 Teacher/Professor",
//       "🏛️ IAS/IPS/IFS (Government Services)",
//       "🎨 Designer/Creative Professional",
//       "📊 Data Analyst/Statistician",
//       "🔬 Research Scientist",
//       "💰 Chartered Accountant/Financial Advisor",
//       "📰 Journalist/Content Creator",
//       "🧠 Psychologist/Counselor",
//       "🤝 Social Worker/NGO Professional",
//       "🏅 Sportsperson/Athlete",
//       "🪖 Army Officer",
//       "✍️ Other (please specify)",
//     ],
//   },
//   {
//     title: "Question 8",
//     prompt: "What kind of work environment do you feel you would thrive in?",
//     name: "thriving_work_environment",
//     options: [
//       "🖥️ Corporate/office setup",
//       "🔬 Research labs, scientific environment",
//       "⚖️ Courtrooms/legal environment",
//       "🚀 Startups/business creation",
//       "🎭 Creative industries (media, design, content)",
//       "👩‍🏫 Education, teaching, mentoring",
//       "❤️ Social work, NGOs",
//       "🏥 Medical/healthcare",
//       "🏛️ Government services",
//       "✍️ Other (please specify)",
//     ],
//   },
//   {
//     title: "Question 9",
//     prompt: "Which optional subject(s) did you choose for Class 12th?",
//     name: "class_12th_optional_subject",
//     options: [
//       "💻 Computer Science",
//       "🖥️ Informatics Practices",
//       "📉 Economics",
//       "🏛️ History",
//       "🗳️ Political Science",
//       "🧑‍🤝‍🧑 Sociology",
//       "🧠 Psychology",
//       "💼 Entrepreneurship",
//       "🎨 Fine Arts",
//       "🏃‍♂️ Physical Education",
//       "✍️ Other (please specify)",
//     ],
//   },
//   {
//     title: "Question 10",
//     prompt: "What made you choose this particular optional subject?",
//     name: "reason_for_optional_subject",
//     options: [
//       "❤️ Genuine Interest",
//       "💼 Good career prospects",
//       "📈 I was good at it earlier",
//       "👨‍👩‍🏫 Suggested by parents or teachers",
//       "👬 Peer pressure",
//       "✍️ Other (please specify)",
//     ],
//   },
//   {
//     title: "Question 11",
//     prompt:
//       "If you had to start your own YouTube channel, what would it most likely be about?",
//     name: "youtube_channel_topic",
//     options: [
//       "🎓 Science or Tech experiments",
//       "🗳️ Political / Social commentary or News analysis",
//       "💼 Business hacks / Finance / Career advice",
//       "🎨 Art / Creativity / Personal expression",
//       "🎤 Public speaking / Debates / Motivation",
//       "🎮 Gaming or Entertainment",
//     ],
//   },
//   {
//     title: "Question 12",
//     prompt:
//       "Is there any specific dream, goal, or profession you are secretly passionate about?",
//     name: "secret_passion_open_ended",
//     //options: [],
//   },
// ];

// export const tenth_grade_questions = [
//   {
//     title: "Q1.",
//     prompt:
//       "Which subjects do you feel most confident in, without needing much help? (Choose the ones you naturally perform well in.)",
//     name: "academic_strengths_subject",
//     options: [
//       "📐 Mathematics",
//       "⚗️ Physics / Chemistry (✓ Science – PCM)",
//       "🧬 Biology / Environmental Science (✓ Science – PCB)",
//       "🗺️ History / Political Science / Geography / Current Affairs (✓ Arts)",
//       "💼 Business Studies / Accounts / Economics (✓ Commerce)",
//       "💻 Computers / Tech / Coding",
//     ],
//   },
//   {
//     title: "Q2.",
//     prompt:
//       "Which of these tasks do you enjoy doing the most or feel naturally good at?",
//     name: "academic_strengths_task",
//     options: [
//       "🧠 Solving logical problems, numerical questions, or learning and experimenting in physics or chemistry (✓ Science/Math/PCM)",
//       "🧬 Learning about the human body, nature, or doing experiments related to biology (✓ Science/Biology/PCB)",
//       "🗳️ Understanding society, politics, or history and discussing current events (✓ Arts/Social Science)",
//       "💹 Thinking of business ideas, planning money, or managing things like a startup (✓ Commerce/Business)",
//       "✍️ Explaining concepts in a simple way to people or writing with clarity and facts (✓ Arts/Teaching/Communication)",
//     ],
//   },
//   /*{
//     title: "Q3.",
//     prompt:
//       "How would you rate your recent marks in the following subjects? (Choose the most appropriate range for each)",
//     name: "academic_strengths_marks",
//     options: [
//       "📐 Math: 40–50%, 50–60%, 60–70%, 70–80%, 80–90%, 90%+",
//       "⚗️ Science: 40–50%, 50–60%, 60–70%, 70–80%, 80–90%, 90%+",
//       "🗺️ Social Science: 40–50%, 50–60%, 60–70%, 70–80%, 80–90%, 90%+",
//       "📝 English/Hindi: 40–50%, 50–60%, 60–70%, 70–80%, 80–90%, 90%+",
//       "💻 Computer/IT/Other: 40–50%, 50–60%, 60–70%, 70–80%, 80–90%, 90%+",
//     ],
//   },*/
//   {
//     title: "Q3.",
//     prompt:
//       "How would you rate your recent marks in the following subjects? (Choose the most appropriate range for each)",
//     name: "academic_strengths_marks",
//     options: {
//       Math: ["40–50%", "50–60%", "60–70%", "70–80%", "80–90%", "90%+"],
//       Science: ["40–50%", "50–60%", "60–70%", "70–80%", "80–90%", "90%+"],
//       SocialScience: ["40–50%", "50–60%", "60–70%", "70–80%", "80–90%", "90%+"],
//       EnglishHindi: ["40–50%", "50–60%", "60–70%", "70–80%", "80–90%", "90%+"],
//       ComputerIT: ["40–50%", "50–60%", "60–70%", "70–80%", "80–90%", "90%+"],
//     },
//   },
//   {
//     title: "Q4.",
//     prompt:
//       "At 30 years of age, what kind of profession do you see yourself confidently working in with both financial stability and satisfaction?",
//     name: "natural_inclination_profession",
//     options: [
//       "💻 Software Developer / Engineer",
//       "📊 CA / Finance Expert / Analyst",
//       "🩺 Doctor / Healthcare Professional",
//       "🏅 Sportsperson",
//       "🏛️ Government Officer (like IAS, IPS)",
//       "⚖️ Lawyer / Legal Expert",
//       "🎓 Teacher / Professor / Educator",
//       "🧑‍💼 Entrepreneur / Business Owner",
//       "🔬 Researcher / Scientist",
//       "❤️ Social Worker / NGO Sector",
//     ],
//   },
//   {
//     title: "Q5.",
//     prompt: "What kind of topics or activities excite you the most?",
//     name: "natural_inclination_excite",
//     options: [
//       "🛠️ Building or fixing things, exploring how machines or code works",
//       "🧠 Understanding human behavior, psychology, or life science",
//       "🗳️ Discussing politics, governance, or debating current affairs",
//       "💼 Planning business ideas or money-related decisions",
//       "✍️ Writing essays, poems, or explaining concepts creatively",
//     ],
//   },
//   {
//     title: "Q6.",
//     prompt: "What kind of workplace do you imagine yourself enjoying the most?",
//     name: "natural_inclination_workplace",
//     options: [
//       "🏛️ A government office or administrative workplace",
//       "🏢 A modern corporate office with innovation and tech",
//       "🏥 A hospital, clinic, or research lab",
//       "🏫 A classroom, college, or educational institute",
//       "🚀 Your own startup/business setup",
//     ],
//   },
//   {
//     title: "Q7.",
//     prompt: "In your free time, what do you mostly enjoy doing?",
//     name: "natural_inclination_freetime",
//     options: [
//       "📚 Reading biographies or inspirational stories",
//       "🧘 Watching motivational talks or spiritual content",
//       "🌐 Gaining knowledge about tech, math, history, polity, or current affairs",
//       "⚽ Playing sports or engaging in physical activities",
//       "👥 Hanging out with friends or scrolling social media",
//     ],
//   },
//   {
//     title: "Q8.",
//     prompt:
//       "Do you feel influenced by any of the following while choosing your future career path?",
//     name: "natural_inclination_influence",
//     options: [
//       "👪 My parents’ suggestions or expectations",
//       "👫 Trends or what my friends are choosing",
//       "📲 Social media or celebrity inspiration",
//       "💭 I choose independently based on what I enjoy",
//     ],
//   },
//   {
//     title: "Q9.",
//     prompt: "What would you enjoy more participating in?",
//     name: "natural_inclination_participate",
//     options: [
//       "🗣️ Debates, quizzes, or political discussions",
//       "🧪 Tech fairs, science exhibitions, or coding contests",
//       "🤝 Group projects or team-based activities",
//       "✍️ Creative writing or speech competitions",
//       "💼 Market simulations, business idea pitch events",
//     ],
//   },
//   {
//     title: "Q10.",
//     prompt: "What do you love doing as a hobby, where you lose track of time?",
//     name: "emotive_psyche_hobby",
//     options: [
//       "🧩 Solving puzzles, problems, or logical games",
//       "🌿 Exploring nature or learning about life science",
//       "📰 Reading history, polity, or watching news",
//       "💡 Thinking of new business ideas or planning finances",
//       "🗣️ Writing, speaking, or teaching people",
//     ],
//   },
//   {
//     title: "Q11.",
//     prompt: "What motivates you more in life?",
//     name: "emotive_psyche_motivation",
//     options: [
//       "🏛️ Achieving a respected position like an IAS officer or lawyer",
//       "🔬 Doing deep research in science/math and contributing to innovation",
//       "💼 Running a successful business or managing money well",
//       "❤️ Helping people by teaching, treating, or guiding them",
//     ],
//   },
//   {
//     title: "Q12.",
//     prompt:
//       "If you had to choose, which of these is most important to you in your career?",
//     name: "emotive_psyche_priority",
//     options: [
//       "🎖️ Gaining social respect and recognition",
//       "💰 Earning a lot of money and living comfortably",
//       "🧘 Inner satisfaction through meaningful work",
//       "🚀 Contributing to science, tech, or society at large",
//     ],
//   },
//   {
//     title: "Q13.",
//     prompt: "Which of these activities do you relate to most naturally?",
//     name: "emotive_psyche_activities",
//     options: [
//       "🧠 Solving math problems or science-related questions",
//       "🗳️ Reading and discussing current affairs or political events",
//       "🎓 Teaching or sharing knowledge in history, polity, geography",
//       "✍️ Writing poems, essays, or stories (literature)",
//       "📊 Managing money, understanding finance and economy",
//     ],
//   },
//   {
//     title: "Q14.",
//     prompt: "Is anyone else influencing your subject or career decision?",
//     name: "emotive_psyche_influence",
//     options: [
//       "👪 My parents want me to take a certain stream",
//       "👫 My friends or peers are choosing it, so I feel pressured",
//       "📲 It’s a trending or high-paying career (social media, news, etc.)",
//       "🧭 I want to follow my inner calling, even if it’s uncommon",
//     ],
//   },
//   {
//     title: "Q15:",
//     prompt:
//       "What motivates you the most when you think about your future career?",
//     name: "emotive_psyche_future_motivation",
//     options: [
//       "💸 Only money matters to me — I don’t care much about respect or recognition.",
//       "🤝 I want a career that gives me respect and decent earnings, even if I’m not very famous.",
//       "🌟 I want a career where I earn well, gain respect, and make a big name for myself — I want to be known.",
//     ],
//   },
// ];

// export const graduate_questions = [
//   {
//     title: "Question 1",
//     prompt: "What degree are you pursuing or have completed?",
//     name: "graduate_degree",
//     options: [
//       "🎓 B.A. (Humanities, Social Sciences)",
//       "💼 B.Com",
//       "📊 BBA",
//       "🖥️ B.Sc. (Non-CS)",
//       "✍️ Other (please specify)",
//     ],
//   },
//   {
//     title: "Question 2",
//     prompt: "How do you feel about working in the IT or digital world?",
//     name: "it_digital_world_feeling",
//     options: [
//       "💻 I’m very interested and open to learning",
//       "🤔 Curious but unsure if I’m the right fit",
//       "😬 I find it overwhelming",
//       "🙅‍♂️ I’ve never really considered it",
//     ],
//   },
//   {
//     title: "Question 3",
//     prompt: "What type of tech role would you be most comfortable with?",
//     name: "tech_role_comfort",
//     options: [
//       "🧠 Minimal or no coding (I prefer using tools, not building them)",
//       "🔁 A mix — I’m okay with a bit of coding + logic-based work",
//       "👨‍💻 I’m open to hardcore coding roles if I get proper training",
//       "❌ Not sure yet — I need help figuring it out",
//     ],
//   },
//   {
//     title: "Question 4",
//     prompt: "Which of these activities feel most natural and enjoyable to you?",
//     name: "natural_enjoyable_activities",
//     options: [
//       "💬 Talking to people, explaining things clearly",
//       "🧾 Preparing documents, organizing information",
//       "📈 Making plans, managing small projects",
//       "🤝 Handling clients and their queries",
//       "📊 Working with data, charts, or reports",
//       "🛍️ Understanding markets and customer needs",
//       "🎨 Designing things (social posts, visuals, presentations)",
//       "📱 Exploring apps, websites, or digital tools",
//       "✍️ Creating content (writing, scripting, etc.)",
//     ],
//   },
//   {
//     title: "Question 5",
//     prompt:
//       "Which of these best describes your comfort with technical tools or software?",
//     name: "tech_tools_comfort",
//     options: [
//       "🧑‍🏫 I’ve used MS Excel, Google Docs, and a few online tools",
//       "📱 I enjoy exploring new apps, dashboards, or platforms",
//       "🧩 I’ve tried basic coding or logic-based tools (like Scratch, HTML, Excel formulas)",
//       "🧠 I’ve never tried but I’m eager to learn",
//       "🙈 I avoid tech stuff as much as I can",
//     ],
//   },
//   {
//     title: "Question 6",
//     prompt:
//       "If you had to join a company tomorrow, which kind of role would you feel confident starting in?",
//     name: "confident_starting_role",
//     options: [
//       "🗣️ Support/Client Interaction (solving queries, managing relationships)",
//       "📊 Business/Data Analysis (Excel, dashboards, trends)",
//       "🎯 Marketing or Sales roles (outreach, content, social media)",
//       "📝 Content/Documentation/Operations",
//       "📂 Project/Team coordination roles",
//       "💻 Tech Assistant/Tester (QA, basic testing, feedback)",
//       "🤷‍♂️ Not sure yet — that’s why I’m here!",
//     ],
//   },
//   {
//     title: "Question 7",
//     prompt: "What's your biggest goal right now?",
//     name: "biggest_goal",
//     options: [
//       "💼 Get a stable job quickly",
//       "🚀 Build a long-term career in a growing field",
//       "🧠 Learn skills that are in demand",
//       "💰 Earn well and be independent",
//       "🔄 Shift from a stuck or unclear career path",
//     ],
//   },
//   {
//     title: "Question 8",
//     prompt: "How do you prefer learning new things?",
//     name: "learning_preference",
//     options: [
//       "🎥 Watching short videos and tutorials",
//       "🧑‍🏫 Doing practical, hands-on exercises",
//       "📚 Reading and following step-by-step guides",
//       "🤝 Discussing with mentors or peers",
//       "🤷‍♀️ Haven’t figured out my learning style yet",
//     ],
//   },
//   {
//     title: "Question 9",
//     prompt: "What kind of work environment do you see yourself thriving in?",
//     name: "work_environment_preference",
//     options: [
//       "🧍‍♂️ Flexible and creative",
//       "🧑‍🤝‍🧑 Structured with clear roles",
//       "💬 Interactive and people-facing",
//       "🧘 Calm, task-focused and less social",
//       "🌐 Remote work with digital tools",
//       "🏢 Corporate office with team setup",
//     ],
//   },
//   {
//     title: "Question 10",
//     prompt:
//       "Lastly, if you had no limitations — what kind of work would you love to do every day? (e.g., help people, solve problems, build systems, create ideas, travel, learn tech, etc.)",
//     name: "ideal_work_no_limitations",
//     //options: [],
//   },
// ];

export const tenth_grade_questions = [
  {
    title: "Q1.",
    prompt:
      "Which subjects do you feel most confident in, without needing much help?",
    name: "academic_strengths_subject",
    options: [
      "📐 Mathematics",
      "⚗️ Physics / Chemistry",
      "🧬 Biology / Environmental Science",
      "🗺️ History / Political Science / Geography / Current Affairs",
      "💼 Business Studies / Accounts / Economics",
      "💻 Computers / Tech / Coding",
    ],
  },
  {
    title: "Q2.",
    prompt:
      "Which of these areas do you enjoy the most or feel naturally drawn to?",
    name: "stream_inclination",
    options: [
      "🧠 Solving physics, chemistry, or math-based problems (PCM)",
      "🧬 Learning about the human body, diseases, environment, and biology (PCB)",
      "💹 Learning how businesses and entrepreneurs work, and how finance creates impact (Commerce)",
      "🗳️ Exploring history, politics, society, and great leaders (Arts)",
      "❓ I enjoy multiple things and haven't figured it out yet",
    ],
  },
  {
    title: "Q3.",
    prompt: "How would you rate your recent marks in the following subjects?",
    name: "academic_strengths_marks",
    options: {
      Math: ["40–50%", "50–60%", "60–70%", "70–80%", "80–90%", "90%+"],
      Science: ["40–50%", "50–60%", "60–70%", "70–80%", "80–90%", "90%+"],
      "Social Science": [
        "40–50%",
        "50–60%",
        "60–70%",
        "70–80%",
        "80–90%",
        "90%+",
      ],
      "English/Hindi": [
        "40–50%",
        "50–60%",
        "60–70%",
        "70–80%",
        "80–90%",
        "90%+",
      ],
      "Computer IT": ["40–50%", "50–60%", "60–70%", "70–80%", "80–90%", "90%+"],
    },
  },
  {
    title: "Q4.",
    prompt:
      "At 30 years of age, what kind of profession do you see yourself in?",
    name: "future_profession_goal",
    options: [
      "💻 Software Developer / Engineer",
      "📊 Finance Professional / CA / Analyst",
      "🩺 Doctor / Healthcare",
      "🏅 Sportsperson",
      "🏛️ Government Officer (IAS, IPS)",
      "⚖️ Lawyer / Legal Expert",
      "🎓 Teacher / Educator",
      "🧑‍💼 Business Owner / Entrepreneur",
      "🔬 Scientist / Researcher",
      "❤️ Social Worker / NGO",
    ],
  },
  {
    title: "Q5.",
    prompt: "Which of these interests or hobbies reflect you the most?",
    name: "natural_hobbies",
    options: [
      "✍️ Writing stories, poems, or expressing your thoughts clearly",
      "🎨 Using design/editing tools (like Canva, Figma, etc.) to create digital content",
      "🧪 Learning how science and math concepts work in real life",
      "🎤 Speaking confidently, debating, or sharing opinions",
      "🚀 Learning how businesses run and how entrepreneurs earn, grow, and impact society",
    ],
  },
  {
    title: "Q6.",
    prompt: "What kind of workplace excites you the most?",
    name: "exciting_workplace",
    options: [
      "🏛️ Government office setup",
      "🏢 Tech/startup office space",
      "🏥 Hospital or Research Lab",
      "🏫 School or College",
      "🚀 Own business / Remote work",
    ],
  },
  {
    title: "Q7.",
    prompt:
      "How do you usually spend your free time — when no one is forcing you?",
    name: "free_time_activity",
    options: [
      "📚 Reading biographies, motivational or spiritual content",
      "🗳️ Watching or reading about history, political events, or current affairs",
      "🌐 Exploring new tech, coding, or trying AI tools and new apps",
      "⚽ Playing indoor or outdoor sports",
    ],
  },
  {
    title: "Q8.",
    prompt:
      "Do you feel influenced by anyone while choosing your stream or future path?",
    name: "career_influence",
    options: [
      "👪 My parents/family",
      "👫 My friends or classmates",
      "📲 Career trends/social media",
      "💭 I choose based on my own interest",
      "❓ I haven’t figured it out yet",
    ],
  },
  {
    title: "Q9.",
    prompt: "What kind of school activity would you enjoy most or love to try?",
    name: "activity_preference",
    options: [
      "🗣️ Debates, quizzes, or political discussions",
      "🧪 Tech fairs, science exhibitions, coding contests",
      "🤝 Group projects or team-based tasks",
      "✍️ Creative writing or speech competitions",
      "💼 Business idea pitches or finance-related activities",
      "❓ I haven’t figured it out yet",
    ],
  },
  {
    title: "Q10.",
    prompt:
      "If you had to create a YouTube channel or Instagram page, what would you enjoy making content about?",
    name: "youtube_channel_interest",
    options: [
      "🔬 Explaining a science or math topic you learned",
      "🧬 Sharing knowledge about human biology or health",
      "🗳️ Talking about history, politics, or current affairs",
      "🌐 Reviewing apps, talking about tech or coding",
      "⚽ Creating content about sports or fitness",
      "🌟 Talking about inspiring figures like Ratan Tata, Gandhi, Swami Vivekananda, or Subhash Bose",
    ],
  },
  {
    title: "Q11.",
    prompt: "What do you enjoy doing so much that you lose track of time?",
    name: "flow_activity",
    options: [
      "📐 Learning how physics, chemistry, or math concepts work in real life",
      "🧬 Learning about the human body, diseases, nature, and how living beings function",
      "🌐 Exploring technology, coding, apps, or AI",
      "🗣️ Teaching, writing, or sharing thoughts with peers",
      "💼 Learning how businesses work and how entrepreneurs build things",
    ],
  },
  {
    title: "Q12.",
    prompt: "Which of the following describes your personality best?",
    name: "personality_type",
    options: [
      "🧭 I like to lead, speak up, and make an impact",
      "🧘 I prefer calm focus and enjoy working deeply",
      "🤝 I enjoy helping, guiding, or supporting people",
      "💡 I enjoy creating useful things and solving problems",
      "⚖️ I’m a balanced person — calm yet a leader, focused yet a team player",
    ],
  },
  {
    title: "Q13.",
    prompt: "Why do most students around you choose their career paths?",
    name: "career_reason_observed",
    options: [
      "👪 Because of family pressure",
      "💸 For a high-paying or trending career",
      "👫 Because of friends",
      "❤️ Due to their true interest",
      "❓ They’re still figuring it out",
    ],
  },
  {
    title: "Q14.",
    prompt: "Are you confident about the stream/career you want to choose?",
    name: "confidence_stream_choice",
    options: [
      "✅ Yes, I’m confident and clear",
      "❌ No, I feel unsure or confused",
    ],
  },
  {
    title: "Q14.1",
    prompt: "If 'No', what makes you feel unsure? (Select all that apply)",
    name: "unsure_reason_multiple",
    options: [
      "👪 My parents want something else",
      "👫 Friends are influencing my thinking",
      "🤯 Too many options to choose from",
      "📉 I don’t know what I’m good at",
      "🧭 I haven’t explored or thought about it yet",
      "💬 I need proper guidance or help",
    ],
  },
  {
    title: "Q15.",
    prompt: "Which statement feels the most like 'you'? Be honest!",
    name: "self_statement",
    options: [
      "🧭 I love to lead, take charge, and speak up. I want to make an impact in the world.",
      "🧘 I prefer calm focus. I enjoy working quietly and solving things in depth.",
      "🤝 Helping people, mentoring, and guiding makes me happy. I enjoy being supportive.",
      "💡 I like creating something useful, like a project, a tool, or even a small startup.",
    ],
  },
];
export const senior_secondary_questions = [
  {
    title: "Q1.",
    prompt: "Which stream and subjects did you choose after 10th class?",
    name: "stream_chosen",
    options: ["🔬 Science", "💼 Commerce", "🧠 Arts"],
  },
  {
    title: "Q2.",
    prompt: "What was the main reason you chose these subjects?",
    name: "reason_for_subject_choice",
    options: [
      "❤️ Genuine interest",
      "📊 Good marks in 10th",
      "👨‍👩‍👧 Parental or societal pressure",
      "🧑‍🤝‍🧑 Peer influence",
      "🛡️ Seemed like a safe option",
      "😕 Random or unclear",
      "✍️ Other (specify)",
    ],
  },
  {
    title: "Q3.",
    prompt: "Are you confident about the subjects you chose?",
    name: "subject_confidence_level",
    options: [
      "✅ Very confident",
      "⚖️ Somewhat confident",
      "❌ Not confident at all",
    ],
  },
  {
    title: "Q4.",
    prompt:
      "If you had a free hand, which subjects would you love to study? (Multiple select)",
    name: "dream_subjects_multiple",
    options: [
      "🔬 Physics / Chemistry",
      "🧬 Biology",
      "➗ Mathematics",
      "📘 Business Studies",
      "📒 Accountancy",
      "📉 Economics",
      "🏛️ History / Polity / Sociology / Current Affairs",
      "🧠 Psychology",
      "🌍 Geography",
      "✍️ Others",
    ],
  },
  {
    title: "Q5.",
    prompt:
      "If you imagine yourself 5–10 years from now, which profession excites you most?",
    name: "future_profession_excite",
    options: [
      "🩺 Doctor",
      "🛠️ Engineer",
      "⚖️ Lawyer",
      "🧑‍💼 Entrepreneur / Architect",
      "👩‍🏫 Teacher / Professor",
      "🏛️ IAS / IPS / IFS",
      "🎨 Creative Professional",
      "📊 Data Analyst",
      "🔬 Research Scientist",
      "💰 CA / Financial Analyst",
      "📰 Journalist / Content Creator",
      "🧠 Psychologist / Counselor",
      "🤝 NGO/Social Work",
      "🏅 Athlete",
      "🪖 Army Officer",
      "✍️ Other",
    ],
  },
  {
    title: "Q6.",
    prompt: "Which subjects do you truly enjoy studying? (Multiple select)",
    name: "enjoyed_subjects_multiple",
    options: [
      "Physics, Chemistry, Biology",
      "Math",
      "Business Studies / Accountancy / Economics",
      "History / Polity / Sociology",
      "Psychology / Geography / Fine Arts",
      "Other",
    ],
  },
  {
    title: "Q7.",
    prompt: "Which activities do you naturally enjoy the most?",
    name: "enjoyed_activities_multiple",
    options: [
      "🗣️ Public speaking",
      "🧩 Solving logical puzzles",
      "🎨 Creativity / Designing",
      "👩‍💼 Leading teams",
      "📊 Data analysis",
      "📝 Writing / Content",
      "🤝 Helping / Mentoring",
      "🔬 Experiments / Science",
      "💻 Coding, apps",
      "📢 Marketing / Selling",
      "✍️ Other",
    ],
  },
  {
    title: "Q8.",
    prompt: "If you had a YouTube channel, what would it be about?",
    name: "youtube_channel_topic",
    options: [
      "🎓 Science or Tech",
      "🗳️ Social or Political Awareness",
      "💼 Business / Finance",
      "🎨 Art / Creativity",
      "🎤 Debates / Motivation",
      "🎮 Gaming / Fun",
    ],
  },
  {
    title: "Q9.",
    prompt: "What kind of work environment do you see yourself in?",
    name: "preferred_work_environment",
    options: [
      "Corporate",
      "Research / Science",
      "Court / Legal",
      "Creative / Media",
      "Education",
      "Government",
      "Healthcare",
      "NGO / Social",
      "Other",
    ],
  },
  {
    title: "Q10.",
    prompt: "Which optional subject did you choose in Class 12?",
    name: "optional_subject_class_12",
    options: [
      "💻 CS / IP",
      "📉 Economics",
      "🧠 Psychology / History / Political Science",
      "💼 Entrepreneurship",
      "🎨 Fine Arts",
      "🏃 Physical Ed.",
      "✍️ Other",
    ],
  },
  {
    title: "Q11.",
    prompt: "Why did you choose that optional subject?",
    name: "reason_for_optional_subject",
    options: [
      "❤️ Genuine interest",
      "School provided only these options.",
      "💼 Career prospects",
      "📈 Strong earlier performance",
      "👨‍👩‍🏫 Suggested by peer",
      "✍️ Other",
    ],
  },
  {
    title: "Q12.",
    prompt:
      "Now that you’ve been studying your optional subject, how do you feel about your choice?",
    name: "optional_subject_experience",
    options: [
      "✅ Yes — I genuinely enjoy it and it adds to my overall interest or career path",
      "😐 It's okay — not bad, but not something I feel strongly about",
      "❌ No — I don’t find it useful or enjoyable",
      "🤔 I chose it for convenience, but I now feel unsure about its value",
      "💬 I’m still figuring it out",
    ],
  },
  {
    title: "Q13.",
    prompt:
      "Do you feel that your current stream and subject choices are helping you move in the direction you truly want to go in life?",
    name: "stream_alignment",
    options: [
      "✅ Yes — I feel happy, focused, and clear that I’m on the right path",
      "⚖️ Somewhat — I’m not totally sure, but it’s not bad either",
      "❌ No — I feel off-track or unsure",
    ],
  },
  {
    title: "Q13.1",
    prompt:
      "If your answer is 'No', what do you think is the reason? (Choose any that apply)",
    name: "reason_for_misalignment_multiple",
    options: [
      "👪 I chose based on what my parents wanted",
      "🧑‍🤝‍🧑 I followed my friends or peer trend",
      "🧭 I still haven’t figured out what I really want",
      "📚 The subjects I chose aren’t interesting to me anymore",
      "💭 I feel lost, unmotivated, or confused",
      "❓ Other",
    ],
  },
  {
    title: "Q14.",
    prompt: "Which of the following statements feels most like 'you'?",
    name: "personality_style",
    options: [
      "🧭 “I like to lead, take charge, and bring change. I want to create a big impact.”",
      "🧘 “I’m focused and calm. I prefer working deeply on things I care about.”",
      "🤝 “Helping, guiding, or supporting people gives me joy. I value connection.”",
      "💡 “I enjoy building or creating useful things — projects, ideas, or systems.”",
      "⚖️ “I’m a balanced person — calm yet a leader, focused yet a team player.”",
    ],
  },
];
export const graduate_questions = [
  {
    title: "Q1.",
    prompt: "What degree are you pursuing or have completed?",
    name: "graduate_degree",
    options: [
      "🎓 B.A. (Humanities, Social Sciences)",
      "💼 B.Com",
      "📊 BBA",
      "🖥️ B.Sc. (Non-CS)",
      "✍️ Other (please specify)",
    ],
  },
  {
    title: "Q2.",
    prompt: "How do you feel about working in the IT or digital world?",
    name: "it_digital_world_feeling",
    options: [
      "💻 I’m very interested and open to learning",
      "🤔 Curious but unsure if I’m the right fit",
      "😬 I find it overwhelming",
      "🙅‍♂️ I’ve never really considered it",
    ],
  },
  {
    title: "Q3.",
    prompt: "What type of tech role would you be most comfortable with?",
    name: "tech_role_comfort",
    options: [
      "🧠 Minimal or no coding (I prefer using tools, not building them)",
      "🔁 A mix — I’m okay with a bit of coding + logic-based work",
      "👨‍💻 I’m open to hardcore coding roles if I get proper training",
      "❌ Not sure yet — I need help figuring it out",
    ],
  },
  {
    title: "Q4.",
    prompt: "Which of these activities feel most natural and enjoyable to you?",
    name: "natural_enjoyable_activities_multiple",
    options: [
      "💬 Talking to people, explaining things clearly",
      "🧾 Preparing documents, organizing information",
      "📈 Making plans, managing small projects",
      "🤝 Handling clients and their queries",
      "📊 Working with data, charts, or reports",
      "🛍️ Understanding markets and customer needs",
      "🎨 Designing things (social posts, visuals, presentations)",
      "📱 Exploring apps, websites, or digital tools",
      "✍️ Creating content (writing, scripting, etc.)",
    ],
  },
  {
    title: "Q5.",
    prompt:
      "Which of these best describes your comfort with technical tools or software?",
    name: "tech_tools_comfort",
    options: [
      "🧑‍🏫 I’ve used MS Excel, Google Docs, and a few online tools",
      "📱 I enjoy exploring new apps, dashboards, or platforms",
      "🧩 I’ve tried basic coding or logic-based tools (like Scratch, HTML, Excel formulas)",
      "🧠 I’ve never tried but I’m eager to learn",
      "🙈 I avoid tech stuff as much as I can",
    ],
  },
  {
    title: "Q6.",
    prompt:
      "If you had to join a company tomorrow, which kind of role would you feel confident starting in?",
    name: "confident_starting_role",
    options: [
      "🗣️ Support/Client Interaction (solving queries, managing relationships)",
      "📊 Business/Data Analysis (Excel, dashboards, trends)",
      "🎯 Marketing or Sales roles (outreach, content, social media)",
      "📝 Content/Documentation/Operations",
      "📂 Project/Team coordination roles",
      "💻 Tech Assistant/Tester (QA, basic testing, feedback)",
      "🤷‍♂️ Not sure yet — that’s why I’m here!",
    ],
  },
  {
    title: "Q7.",
    prompt: "What's your biggest goal right now?",
    name: "current_biggest_goal",
    options: [
      "💼 Get a stable job quickly",
      "🚀 Build a long-term career in a growing field",
      "🧠 Learn skills that are in demand",
      "💰 Earn well and be independent",
      "🔄 Shift from a stuck or unclear career path",
    ],
  },
  {
    title: "Q8.",
    prompt: "How do you prefer learning new things?",
    name: "learning_preference",
    options: [
      "🎥 Watching short videos and tutorials",
      "🧑‍🏫 Doing practical, hands-on exercises",
      "📚 Reading and following step-by-step guides",
      "🤝 Discussing with mentors or peers",
      "🤷‍♀️ Haven’t figured out my learning style yet",
    ],
  },
  {
    title: "Q9.",
    prompt: "What kind of work environment do you see yourself thriving in?",
    name: "work_environment_preference",
    options: [
      "🧍‍♂️ Flexible and creative",
      "🧑‍🤝‍🧑 Structured with clear roles",
      "💬 Interactive and people-facing",
      "🧘 Calm, task-focused and less social",
      "🌐 Remote work with digital tools",
      "🏢 Corporate office with team setup",
    ],
  },
  {
    title: "Q10.",
    prompt:
      "Lastly, if you had no limitations — what kind of work would you love to do every day?",
    name: "ideal_work_no_limitations",
    // open-ended input (text box in UI)
  },
];
